### ISSUE TITLE
Text style support

### ISSUE THREAD

**Issue by Shikanime** [sfeir-open-source/xlayers#22]
At the moment all text present in the project is using a default black colour and default Robot font family.

The solution i found is simply add a text style parsing implementation in the SketchStyleParserSerivce.

**Comment by Shikanime** [comment]
My current implementation work https://github.com/Shikanime/xlayers/tree/text-styling.
But I discovered that some demo files (md-components-cards-safari.skecth) display inconsistent colours from the preview and editor using the latest MacOS Sketch until we change the colour and save it again.

**Comment by Shikanime** [comment]
I'm having trouble with the BPlist parser, it crashes when it tries to parser kind of dictionary. 🤨
![screenshot at oct 24 14-56-57](https://user-images.githubusercontent.com/22115108/47431825-1790c100-d79d-11e8-98dc-75e43c2839d3.png)

**Comment by Shikanime** [comment]
I notices that only the "text" class width in json and in SketchApp are not the same. Until we resave it with SketchApp. 🤯 🤯

**Comment by manekinekko** [comment]
Can you elaborate on that more in details ?

**Comment by manekinekko** [comment]
Well, well, that's unfortunate. Maybe a bug in SketchApp? Can we prevent this on our side?

**Comment by Shikanime** [comment]
In fact, this seems difficult to prevent even if we create an exception on the "text" class in the style parser that will break correct files.
But if we assume that all demos files could have been corrupted the actual xLayer's style parser work as it should (color and size).

**Comment by manekinekko** [comment]
Fair enough. We should probably organize the demo files by SketchApp version. This would help us quickly identify corrupted versions. Do you still have the different SketchApp versions on your machine?

**Comment by Shikanime** [comment]
I have all SketchApp version from 46 to 52.

**Comment by Shikanime** [comment]
Btw, as you can see the double "text" is also fixed on preview.
![xlayers sketch viewer and codegen 2018-11-23 11-41-27](https://user-images.githubusercontent.com/22115108/48939585-f85c8f00-ef14-11e8-8377-9f965d6d389e.png)
