### ISSUE TITLE
Revert the properties tab group buttons

### ISSUE THREAD

**Issue by manekinekko** [sfeir-open-source/xlayers#34]
**Describe the bug**
The group buttons in the properties tab have been altered when migration to the new MD version.

**Expected behavior**
The expected design is the one on the right (see screenshot)

![image](https://user-images.githubusercontent.com/1699357/47728290-55d72600-dc5e-11e8-92c2-b734a76d8bd6.png)

**Comment by Shikanime** [comment]
Fixed ! 😇

![screencast 2018-10-31 16-42-55](https://user-images.githubusercontent.com/22115108/47800198-16770b00-dd2c-11e8-8dbb-3631406ab3f8.gif)
