### ISSUE TITLE
The rendered design is not centered

### ISSUE THREAD

**Issue by manekinekko** [sfeir-open-source/xlayers#36]
Make sure that the rendered design is well centered.

Suggestion: Make the canvas draggable so the user can move the design around!

![image](https://user-images.githubusercontent.com/1699357/47729065-cc285800-dc5f-11e8-9509-d3b2d72955df.png)

**Comment by Shikanime** [comment]
At the moment the canvas is draggable but i didn't find out how to get a pixel based position from a percent position.
![screencast 2018-10-31 10-49-39](https://user-images.githubusercontent.com/22115108/47780050-e2372680-dcfa-11e8-84af-ed306e879278.gif)
So i let it start at top/left. sfeir-open-source/xlayers@a571b0c2524fc07a83c5fb10e13362935091a140

**Comment by manekinekko** [comment]
Then let's switch to a fixed position, based on the current viewport (even when the viewport gets resized).

**Comment by manekinekko** [comment]
We also need to change the pointer cursor to a move pointer ;)

**Comment by Shikanime** [comment]
Got it.
And i just figure out that the xlayers/xlayers#24 issue can be related to this issue as well.

**Comment by manekinekko** [comment]
awesome sauce 🎊

**Comment by Shikanime** [comment]
Mhhh, maybe I was misunderstood.
When i said that i didn't find out how to convert percent to pixel is because to center the canvas i used `left: 50%` and for the dragging it actually return the pixel offset from the origin point.
At the first drag i need to initialize the origin position to a `{x, y}` from a `top/left: 50%`.

**Comment by manekinekko** [comment]
Try using [`Element.getBoundingClientRect()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) or [`Element.getClientRects()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects).

**Comment by Shikanime** [comment]
The actual result is now center and seem to work well.
![screencast 2018-10-31 15-45-06](https://user-images.githubusercontent.com/22115108/47796650-10316080-dd25-11e8-972a-db5edec3b31e.gif)

**Comment by manekinekko** [comment]
waiting for your PR so I can try it LIVE :)

**Comment by manekinekko** [comment]
@Shikanime can we get the actual PR that fixe this issue?

**Comment by manekinekko** [comment]
fixed by https://github.com/xlayers/xlayers/pull/62
