### ISSUE TITLE
Swith the test runner to Jest

### ISSUE THREAD

**Issue by manekinekko** [sfeir-open-source/xlayers#41]
Use Jest instead of Karma.  

Resource: https://blog.angularindepth.com/integrate-jest-into-an-angular-application-and-library-163b01d977ce

**Comment by Shikanime** [comment]
Doesn't karma have a better integration in Angular instead of Jest?
Is there a motivation behind this change?

**Comment by manekinekko** [comment]
Jest have better ergonomics and is ***usually*** a bit faster than karma. It also have some nice features such as snapshot testing and parallel execution which would be nice to take advantage of.

**Comment by manekinekko** [comment]
fixed by https://github.com/xlayers/xlayers/pull/67
